expense/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from . import views

app_name = 'expense'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.login_user, name="login"),
    url(r'^logout/$', views.logout_user, name='logout'),
    url(r'^register/', views.register, name='register'),
    url(r'^manager/', views.helloworld, name="expense"),
    url(r'^credit/', views.credit, name="credit"),
    url(r'^profile/', views.profile, name="profile"),
    url(r'^history/', views.history, name="history"),


]

manager/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^expense/', include('expense.urls')),
]

expense/models.py
from __future__ import unicode_literals
import random
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext_lazy as _


# Create your models here.

TRANSACTION_TYPE = [
    ('credit', 'Credit'),
    ('debit', 'Debit')

]


class TimeStamp(models.Model):
    created_on = models.DateTimeField(auto_now_add=True, verbose_name=_('Created On'))
    modified_on = models.DateTimeField(auto_now=True, verbose_name=_('Modified On'))

    class Meta:
        abstract = True


class Account(TimeStamp):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    account_no = models.IntegerField(primary_key=True, blank=True)
    monthly_budget = models.FloatField(blank=True, null=True)

    def __unicode__(self):
        return str(self.account_no)

    def create_account_no(self):
        return random.randrange(10 ** 12)

    def save(self, *args, **kwargs):
        if not self.account_no:
            self.account_no = self.create_account_no()
        super(Account, self).save(*args, **kwargs)


class Category(TimeStamp):

    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=63, unique=True, blank=True, null=True, verbose_name='Slug (Auto Fill)')

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):

        if not self.slug:

            self.slug = slugify(self.name)

        super(Category, self).save(*args, **kwargs)


class Transactions(TimeStamp):

    amount = models.FloatField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    transaction_type = models.CharField(max_length=50, choices=TRANSACTION_TYPE)
    comment = models.CharField(max_length=100, blank=True)
    account = models.ForeignKey(Account, on_delete=models.CASCADE)

    def __unicode__(self):
        return str(self.amount)

expense/forms.py
from django import forms
from django.contrib.auth.models import User


from .models import Account, Category, Transactions


class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class BudgetForm(forms.ModelForm):

    class Meta:
        model = Account
        fields = ['monthly_budget']


class AccountForm(forms.ModelForm):
    """docstring for AccountForm"""

    class Meta:
        model = Transactions
        fields = ['amount', 'category', 'transaction_type', 'comment','account']

expense/views.py
from django.shortcuts import render, render_to_response, redirect
from django.http import HttpResponseRedirect
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .models import Account, Category, Transactions
from .forms import UserForm, AccountForm, BudgetForm

# Create your views here.


def helloworld(request):
    form = AccountForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        amount = form.cleaned_data['amount']
        category = form.cleaned_data['category']
        transaction_type = form.cleaned_data['transaction_type']
        comment = form.cleaned_data['comment']
        account = form.cleaned_data['account']
        user.save()
        if user is not None:
            if user:
                cat = Category.objects.all()
                return render(request, 'index.html', {'cat': cat})

    context = {
        "form": form
    }

    return render(request, 'index.html', context)



def credit(request):

    return render(request, 'credit.html')


@login_required
@csrf_protect
def profile(request):

        form = BudgetForm(request.POST or None)
        if form.is_valid():
            budget = form.save(commit=False)
            monthly_budget = form.cleaned_data['monthly_budget']
            budget.user = request.user
            budget.save()
            if budget is not None:
                if budget:
                    return render(request, 'profile.html')

        context = {
            "form": form
        }

        return render(request, 'profile.html', context)

def history(request):

    return render(request, 'history.html')


def login_user(request):

    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                account = Account.objects.filter(user=request.user)
                return redirect('/expense/profile/')
            else:
                return render(request, 'login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'login.html', {'error_message': 'Invalid Login'})
    else:
        return render(request, 'login.html')


def logout_user(request):

    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form":form
    }
    return render(request, 'login.html', context)


def register(request):

    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'index.html')

    context = {
        "form": form
    }

    return render(request, 'register.html', context)

expense/templates/base_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Expense Manager{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
      <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
    <script type="text/javascript" href="{% static 'js/index.js' %}"></script>


</head>

<body>
{% block navbar %}
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

    <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

    <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'expense:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'expense:login' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% endblock %}
{% block body %}
{% endblock %}

</body>
</html>

expense/templates/credit.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<h1>Hello Credit</h1>
</body>
</html>

expense/templates/history.html
{% extends 'index.html' %}
{% block title %}Profile{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}



{% endblock %}

expense/templates/index.html
{% extends 'base_login.html' %}
{% block title %}Expense Manager{% endblock %}
{% block login_active %}active{% endblock %}



{% block navbar %}
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

    <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

    <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'expense:expense' %}">Credit/Debit</a></li>
                <li class="{% block login_active1 %}{% endblock %}"><a href="{% url 'expense:profile' %}">Profile</a></li>
                <li class="{% block login_active2 %}{% endblock %}"><a href="{% url 'expense:history' %}">History</a></li>
                <li ass="right" style="position:absolute;right:60px;" class="{% block login_active3 %}{% endblock %}"><a href="{% url 'expense:logout' %}">Logout</a></li>
            </ul>
        </div>

    </div>
</nav>
{% endblock %}
{% block body %}

<div class="container">

  <h2>Enter Details</h2>
  <form role="form" action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {% include 'register_template.html' %}

<div class="form-group">
<input type="submit" class="btn btn-info" value="Submit">
</div>
</form>
</div>



</div>
</body>

{% endblock %}

expense/templates/login.html
{% extends 'base_login.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

<div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'expense:login'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                    </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'expense:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

expense/templates/profile.html
{% extends 'index.html' %}
{% block title %}Profile{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}

<div class="container">
<div class="panel panel-default">
  <div class="panel-body">

{% for field in form %}
{{field.error}}
{% endfor %}

<form  action="/expense/profile/" method="post">

{% csrf_token %}
<h3>Hello ! {{user}}<br><br>
{{user.email}}</h3><br><p><mark>Add your monthly budget</mark></p>

{% include 'register_template.html' %}

<input type="submit" class="btn btn-info" value="Submit">

</form>
</div>
</div>
</div>

<!-- {{user.password}} -->
<!-- {{form.as_ul}} -->


</div>

{% endblock %}

expense/templates/register.html
{% extends 'base_login.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'register_template.html' %}
                    <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'expense:login' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

expense/templates/register_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label" for="title">{{ field.label_tag }}</label>
        <div class="form-control input-lg" >{{ field }}</div>
    </div>
{% endfor %}